       INTEGER FUNCTION  GLOBALINDEX(LIND,GDIM,NP,ME)

!   LIND = INDEX OF AN ELEMENT OF SHEARED ARRAY IN THE LOCAL MEMORY
!   GDIM = GLOBAL DIMENSION OF AN ARRAY TO BE SHEARED AMONG PROCESSORS
!   NP   = NUMBER OF PROCESSOR
!   ME   = INDEX OF THE CALLING PROCESSOR (starting from ZERO)
!  
!   THIS FUNCTION RETURN THE ABSOLUTE INDEX OF THE LOCAL 
!   ARRAY ELEMENT "LIND" 

       IMPLICIT NONE

       INTEGER LIND,GDIM,NP,ME,R,Q
       Q = INT(GDIM/NP)
       R = MOD(GDIM,NP)
       IF((ME+1).LE.R) THEN
         GLOBALINDEX = (Q+1)*ME + LIND
       ELSE
         GLOBALINDEX = Q*ME + R + LIND
       END IF
       RETURN
       END
