
! on T3e substitute MPI_DOUBLE_PRECISION with MPI_REAL
! on other architecture substitute MPI_REAL with MPI_DOUBLE_PRECISION

      SUBROUTINE PARALLEL_SUM_REAL(ARRAY,N)
        IMPLICIT NONE
        INCLUDE 'mpif.h'
        INTEGER N, ERR, I
        REAL*8 ARRAY(N)
        REAL*8 ARRAY_TMP(N)
        CALL MPI_ALLREDUCE(ARRAY,ARRAY_TMP,N,MPI_DOUBLE_PRECISION, 
     &       MPI_SUM,MPI_COMM_WORLD,ERR)
        ARRAY = ARRAY_TMP
        RETURN
      END SUBROUTINE PARALLEL_SUM_REAL

      SUBROUTINE PARALLEL_SUM_COMPLEX(ARRAY,N)
        IMPLICIT NONE
        INCLUDE 'mpif.h'
        INTEGER N, ERR, I
        COMPLEX*16 ARRAY(N)
        COMPLEX*16 ARRAY_TMP(N)
        CALL MPI_ALLREDUCE(ARRAY,ARRAY_TMP,N,MPI_DOUBLE_PRECISION, 
     &       MPI_SUM,MPI_COMM_WORLD,ERR)
        ARRAY = ARRAY_TMP
        RETURN
      END SUBROUTINE PARALLEL_SUM_COMPLEX

!
      SUBROUTINE PARALLEL_SUM_INTEGER(ARRAY,N)
        IMPLICIT NONE
        INCLUDE 'mpif.h'
        INTEGER N, ERR, I
        INTEGER ARRAY(N)
        INTEGER ARRAY_TMP(N)
        CALL MPI_ALLREDUCE(ARRAY,ARRAY_TMP,N,MPI_INTEGER, 
     &       MPI_SUM,MPI_COMM_WORLD,ERR)
        ARRAY = ARRAY_TMP
      RETURN
      END SUBROUTINE PARALLEL_SUM_INTEGER
!
!
      SUBROUTINE PARALLEL_SUM_REAL_TO(ARRAY_IN,ARRAY_OUT,N)
        IMPLICIT NONE
        INCLUDE 'mpif.h'
        INTEGER N,ERR
        REAL*8 ARRAY_IN(N)
        REAL*8 ARRAY_OUT(N)
        CALL MPI_ALLREDUCE(ARRAY_IN,ARRAY_OUT,N,MPI_DOUBLE_PRECISION, 
     &       MPI_SUM,MPI_COMM_WORLD,ERR)
        RETURN
      END SUBROUTINE PARALLEL_SUM_REAL_TO


      SUBROUTINE PARALLEL_MAX_INTEGER(ARRAY,N)
        IMPLICIT NONE
        INCLUDE 'mpif.h'
        INTEGER N, I, IERR
        INTEGER ARRAY(N)
        INTEGER IWORK(N)
        CALL MPI_ALLREDUCE(ARRAY,IWORK,N,MPI_INTEGER, 
     &       MPI_MAX,MPI_COMM_WORLD,IERR)
        ARRAY = IWORK
        RETURN
      END SUBROUTINE PARALLEL_MAX_INTEGER

      SUBROUTINE PARALLEL_MIN_INTEGER(ARRAY,N)
        IMPLICIT NONE
        INCLUDE 'mpif.h'
        INTEGER N, I, IERR
        INTEGER ARRAY(N)
        INTEGER IWORK(N)
        CALL MPI_ALLREDUCE(ARRAY,IWORK,N,MPI_INTEGER,
     &       MPI_MIN,MPI_COMM_WORLD,IERR)
        ARRAY = IWORK
        RETURN
      END SUBROUTINE PARALLEL_MIN_INTEGER


      SUBROUTINE PARALLEL_MAX_REAL(ARRAY,N)
        IMPLICIT NONE
        INCLUDE 'mpif.h'
        INTEGER N, IERR
        REAL*8  ARRAY(N)
        REAL*8  RWORK(N)
        CALL MPI_ALLREDUCE(ARRAY,RWORK,N,MPI_DOUBLE_PRECISION, 
     &       MPI_MAX,MPI_COMM_WORLD,IERR)
        ARRAY = RWORK
        RETURN
      END SUBROUTINE PARALLEL_MAX_REAL

